// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POSEIDON.Models;

namespace POSEIDON.Migrations
{
    [DbContext(typeof(PoseidonContext))]
    [Migration("20210916140538_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("POSEIDON.Models.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Activity")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("OriginId")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableId")
                        .HasDatabaseName("IX_HistoryTable");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ctrUser");

                    b.HasIndex("Activity", "TableId", "Timestamp")
                        .HasDatabaseName("IX_Activity");

                    b.HasIndex("TableId", "OriginId", "Activity")
                        .HasDatabaseName("IX_History");

                    b.ToTable("HISTORY");
                });

            modelBuilder.Entity("POSEIDON.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ROL");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ROOT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ADMIN"
                        },
                        new
                        {
                            Id = 3,
                            Name = "USER"
                        });
                });

            modelBuilder.Entity("POSEIDON.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("TABLE");
                });

            modelBuilder.Entity("POSEIDON.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Aditional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Authorized")
                        .HasColumnType("bit");

                    b.Property<string>("Charge")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Destine")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InternalPhone")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("UI_KeyUser");

                    b.ToTable("USER");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Account = "ARMADA\\DIAP197",
                            Active = true,
                            Aditional = "39-6d-19-5b-cf-1e-33-2a-3f-e0-48-31-50-5a-5d-1b",
                            Authorized = true,
                            Charge = "PROGRAMADOR",
                            Degree = "CP",
                            Destine = "DIAP",
                            FirstName = "DENIS ADRIEL",
                            InternalPhone = "122462",
                            Key = "CHAMBI",
                            LastName = "CHAMBI",
                            Password = "cd-37-be-e4-56-fe-d5-89-9a-0f-65-eb-47-73-34-f2-5e-e4-67-9f-d8-8d-16-a4-0a-f4-7a-57-6f-0e-c9-8e"
                        },
                        new
                        {
                            Id = 2,
                            Account = "ARMADA\\DIAP204",
                            Active = true,
                            Aditional = "11-57-83-0e-a6-10-e2-44-e4-a9-1b-c0-d8-21-95-0b",
                            Authorized = true,
                            Charge = "ENCARGADO SEGUIMIENTO PROFESIONAL",
                            Degree = "SM",
                            Destine = "DIAP",
                            FirstName = "JOSE",
                            InternalPhone = "122462",
                            Key = "SALINAS",
                            LastName = "SALINAS",
                            Password = "0e-f4-91-d2-58-c3-84-a7-2c-dc-d0-e0-b5-7c-9e-3a-27-87-b6-e0-41-fa-b4-cd-b9-e6-6f-75-a9-5b-6d-20"
                        },
                        new
                        {
                            Id = 3,
                            Account = "ARMADA\\DIAP233",
                            Active = true,
                            Aditional = "2f-86-19-d7-df-a4-06-3e-59-66-92-a9-bc-df-97-b5",
                            Authorized = true,
                            Charge = "AUXILIAR SEGUIMIENTO PROFESIONAL",
                            Degree = "CP",
                            Destine = "DIAP",
                            FirstName = "MARIO",
                            InternalPhone = "122462",
                            Key = "TOLABA",
                            LastName = "TOLABA",
                            Password = "81-f4-7a-9d-db-85-88-83-de-3f-a7-26-f1-91-06-40-2f-0c-e0-29-3d-11-01-67-77-bd-77-0f-a0-9b-6d-0a"
                        });
                });

            modelBuilder.Entity("POSEIDON.Models.UserAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Cyte")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperativeSystem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RefreshDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("StillSession")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RefreshToken")
                        .IsUnique()
                        .HasDatabaseName("UI_RefreshToken");

                    b.HasIndex("UserId", "Token")
                        .IsUnique()
                        .HasDatabaseName("UI_Token");

                    b.ToTable("USER_ACCESS");
                });

            modelBuilder.Entity("POSEIDON.Models.UserRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UserId", "RolId")
                        .IsUnique()
                        .HasDatabaseName("UI_UsuarioRol");

                    b.ToTable("USER_ROL");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RolId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            RolId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            RolId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("POSEIDON.Models.History", b =>
                {
                    b.HasOne("POSEIDON.Models.Table", null)
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("POSEIDON.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("POSEIDON.Models.UserAccess", b =>
                {
                    b.HasOne("POSEIDON.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("POSEIDON.Models.UserRol", b =>
                {
                    b.HasOne("POSEIDON.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("POSEIDON.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
